// tier: fast

/**
 * Server exports are directory transactions: preparation may fail without touching the last good export, and a
 * successful replacement preserves files outside the exporter's owned subtrees.
 *
 * Run: npx tsx test/export-transaction.test.ts
 */
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { textFile } from '../src/core/export/files';
import { writeExportFolder } from '../src/server/routes/export';
import { check, failures } from './check';

const work = await mkdtemp(join(tmpdir(), 'slopesmith-export-transaction-'));
const out = join(work, 'TESTMTN');
const text = async (path: string) => readFile(path, 'utf8');
const leftovers = async () => (await readdir(work)).filter(name => name !== 'TESTMTN');

try {
  await mkdir(join(out, 'Owned'), { recursive: true });
  await writeFile(join(out, 'Owned', 'old.txt'), 'old generated bytes');
  await writeFile(join(out, 'keep.txt'), 'user-owned bytes');

  await writeExportFolder(out, {
    remove: ['Owned'],
    files: [textFile('Owned/new.txt', 'new generated bytes')],
    log: [],
  });
  check(await text(join(out, 'Owned', 'new.txt')) === 'new generated bytes',
    'a successful export swaps in the complete newly generated tree');
  check(await text(join(out, 'keep.txt')) === 'user-owned bytes',
    'the staged tree preserves files outside the exporter-owned paths');
  check((await readdir(join(out, 'Owned'))).join(',') === 'new.txt',
    'owned paths are replaced as a snapshot, so retired output cannot survive');
  check((await leftovers()).length === 0,
    'a successful commit removes its sibling staging and backup directories');

  // A file at `Blocked` makes preparation of `Blocked/child.txt` fail inside the private staging copy. The live
  // export must remain byte-for-byte readable and no partially written child may appear there.
  await writeFile(join(out, 'Blocked'), 'last good blocker');
  let rejected = false;
  try {
    await writeExportFolder(out, {
      remove: [],
      files: [textFile('Owned/replaced-before-failure.txt', 'partial'), textFile('Blocked/child.txt', 'cannot land')],
      log: [],
    });
  } catch { rejected = true; }
  check(rejected, 'a staging write error rejects the export');
  check(await text(join(out, 'Owned', 'new.txt')) === 'new generated bytes'
    && (await readdir(join(out, 'Owned'))).join(',') === 'new.txt',
  'a failed preparation leaves the last good generated output untouched');
  check(await text(join(out, 'Blocked')) === 'last good blocker'
    && await text(join(out, 'keep.txt')) === 'user-owned bytes',
  'a failed preparation leaves every pre-existing destination byte untouched');
  check((await leftovers()).length === 0,
    'a failed preparation cleans its private staging directory without creating a backup');
} finally {
  await rm(work, { recursive: true, force: true });
}

if (failures) process.exitCode = 1;
