/**
 * Settings ▸ About — where the project lives (GitHub, Discord), then the disclaimers and third-party notices,
 * shown inside the app.
 *
 * The legal half is not decoration. Apache-2.0 section 4(d) lets a work satisfy its NOTICE obligation in the
 * NOTICE file, in the documentation, OR "within a display generated by the Derivative Works, if and
 * wherever such third-party notices normally appear". A built Slopesmith bundles browser
 * dependencies into dist/ — three, lil-gui, livekit-client and friends — so whoever deploys it is
 * redistributing them. Shipping the notices inside the app is how that obligation travels with the
 * thing that incurs it, instead of resting on the operator remembering to copy a file.
 *
 * **Every long text below is imported, never retyped.** Repository notices use `?raw`; npm dependency
 * notices come from a build-time virtual module generated from the installed package tree. A hand-written
 * copy here would be one more thing to drift out of date, and licence text is exactly where drift is least
 * acceptable — ISC and MIT both ask for *the* notice, not an approximation of it.
 */

import slopesmithNotice from '../../../../NOTICE?raw';
import lucideLicense from '../../../../ThirdPartyNotices/Lucide-LICENSE.txt?raw';
import dependencyNotices from 'virtual:slopesmith-dependency-notices';

const RIGHTSHOLDER_CONTACT = 'contact@transparentsource.org';
/** The same two links the repository README gives. */
const PROJECT_LINKS = [
  { label: 'GitHub', href: 'https://github.com/swax/OpenSlope', note: 'source, issues and releases' },
  { label: 'Discord', href: 'https://discord.gg/QFnt2x9vZ9', note: 'meet other course creators and get help' },
] as const;

export const aboutPanelCss = `
.sp-settings .about { display: flex; flex-direction: column; gap: 14px; }
.sp-settings .about h4 { margin: 0 0 4px; font-size: 13px; color: #e9f5ff; }
.sp-settings .about p { margin: 0 0 6px; line-height: 1.5; color: #b9cbdb; }
.sp-settings .about .about-links { display: flex; flex-direction: column; gap: 6px; margin: 2px 0 0;
  padding: 0; list-style: none; }
.sp-settings .about .about-links li { color: #8fa6ba; }
.sp-settings .about .about-links a { font-weight: 600; }
.sp-settings .about .about-callout { padding: 9px 11px; border-left: 3px solid #4b85b5;
  background: #101d29; border-radius: 0 4px 4px 0; }
.sp-settings .about .about-callout strong { color: #e9f5ff; }
.sp-settings .about a { color: #7fc3ff; }
.sp-settings .about details { border: 1px solid #1d3346; border-radius: 4px; background: #0d1822; }
.sp-settings .about summary { padding: 7px 10px; cursor: pointer; color: #d7e3f0; font-size: 12px; }
.sp-settings .about summary:hover { color: #e9f5ff; background: #111f2c; }
.sp-settings .about summary:focus-visible { outline: 2px solid #4b85b5; outline-offset: -2px; }
.sp-settings .about pre { margin: 0; padding: 9px 11px; border-top: 1px solid #1d3346;
  max-height: 260px; overflow: auto; white-space: pre-wrap; word-break: break-word;
  font: 11px/1.45 ui-monospace, Consolas, monospace; color: #9fb4c6; }
`;

/** One collapsed block holding a verbatim licence or notice. Collapsed because these are reference
 *  texts: a reader wants to know they are here, not to scroll past them to reach the next control. */
function verbatim(summary: string, body: string): HTMLDetailsElement {
  const details = document.createElement('details');
  const head = document.createElement('summary');
  head.textContent = summary;
  const pre = document.createElement('pre');
  pre.textContent = body.trimEnd();
  details.append(head, pre);
  return details;
}

function paragraph(html: string): HTMLParagraphElement {
  const p = document.createElement('p');
  p.innerHTML = html;
  return p;
}

/** Fill the About tab. Static content only — nothing here reads or writes a setting, so it is safe
 *  to build once when the dialog is constructed. */
export function buildAboutPanel(panel: HTMLDivElement): void {
  const root = document.createElement('div');
  root.className = 'about';

  const project = document.createElement('section');
  project.append(Object.assign(document.createElement('h4'), { textContent: 'OpenSlope' }));
  project.append(paragraph(
    'Slopesmith is OpenSlope\'s collaborative, self-hosted editor for building and riding '
    + '<em>SSX Tricky</em>-compatible courses.'));
  const links = document.createElement('ul');
  links.className = 'about-links';
  for (const { label, href, note } of PROJECT_LINKS) {
    const item = document.createElement('li');
    const anchor = Object.assign(document.createElement('a'), {
      href, textContent: label, target: '_blank', rel: 'noopener noreferrer',
    });
    item.append(anchor, ` — ${note}`);
    links.append(item);
  }
  project.append(links);

  const disclaimer = document.createElement('div');
  disclaimer.className = 'about-callout';
  disclaimer.append(paragraph(
    '<strong>This project is not endorsed by or affiliated with EA or its licensors.</strong> '
    + 'Slopesmith is an independent, unofficial tool. SSX and SSX Tricky are trademarks of '
    + 'Electronic Arts Inc.'));
  disclaimer.append(paragraph(
    'Rights in the music and voice performances on a retail disc are held by their publishers, labels '
    + 'and performers and are licensed to Electronic Arts. No grant in this program extends to them.'));

  const yourCopy = document.createElement('section');
  yourCopy.append(Object.assign(document.createElement('h4'), { textContent: 'Retail game data' }));
  yourCopy.append(paragraph(
    'Slopesmith reads levels, textures and audio that you extracted from a disc image you made from '
    + 'your own copy of the game. That material is derived from Electronic Arts\' copyrighted work and '
    + 'stays in folders excluded from version control. OpenSlope grants no rights in it; you are responsible '
    + 'for determining whether your use is permitted by applicable law and contractual terms. Publishing a '
    + 'course, a world or a repacked image that carries it is outside what this project licenses or condones.'));

  const contact = document.createElement('section');
  contact.append(Object.assign(document.createElement('h4'), { textContent: 'Rightsholder enquiries' }));
  contact.append(paragraph(
    `If you hold rights in something you believe this project carries, write to `
    + `<a href="mailto:${RIGHTSHOLDER_CONTACT}">${RIGHTSHOLDER_CONTACT}</a> and we will act on a `
    + 'specific, good-faith request about specific material. Security reports go through a different '
    + 'channel — see SECURITY.md in the repository.'));

  const notices = document.createElement('section');
  notices.append(Object.assign(document.createElement('h4'), { textContent: 'Licences and notices' }));
  notices.append(paragraph(
    'Slopesmith is Apache-2.0. The texts below are the ones this build ships; they are reproduced '
    + 'verbatim from the repository rather than summarised.'));
  notices.append(verbatim('Slopesmith NOTICE — scope, third-party components, generated assets',
                          slopesmithNotice));
  notices.append(verbatim('Lucide (icon artwork) — ISC, with Feather-derived icons MIT',
                          lucideLicense));
  notices.append(verbatim('Bundled npm dependencies and runtime closure — generated legal text',
                          dependencyNotices));
  notices.append(paragraph(
    '<strong>Deploying this?</strong> Keep <code>ThirdPartyNotices/npm-browser-dependencies.txt</code> '
    + 'with <code>dist/</code>. It is generated from the same checked package inventory as the panel above; '
    + 'the build fails if Vite bundles a package that the inventory does not name, or stops bundling one it does.'));

  root.append(project, disclaimer, yourCopy, contact, notices);
  panel.appendChild(root);
}
