// <auto-generated>
// Generated from Slopesmith/tools/ride_response.cs.txt and Trailmap/specs/data/ride-v1.json.
// Edit those sources, then regenerate.
// </auto-generated>
using UnityEngine;

namespace OpenSlope.VrcPlugin
{
    public partial class RideableBoard
    {
        // [Trailmap: 330-resistance] Recovered coefficients.
        // Dimensionless edge-mismatch multipliers; mode 1 or matching edges use unity.
        private const float RESPONSE_STANCE_MODE0_MISMATCH = 0.8499836326f;
        private const float RESPONSE_STANCE_OTHER_MISMATCH = 0.699878335f;

        // [Trailmap: 330-resistance] Recovered coefficients in the existing metre-based formulation.
        // Stat and boost scales are dimensionless; speedScale converts m/s to x=abs(u)/10; unchargedDrag and
        // skidDrag are in 1/s.
        private const float RESPONSE_FORWARD_MODE2_LINEAR_BASE = 0.707642436f;
        private const float RESPONSE_FORWARD_MODE2_LINEAR_STAT_SCALE = 0.3019791245f;
        private const float RESPONSE_FORWARD_LINEAR_BASE = 1.0649821758f;
        private const float RESPONSE_FORWARD_LINEAR_STAT_SCALE = 0.3084552288f;
        private const float RESPONSE_FORWARD_QUADRATIC_BASE = 1.2848105431f;
        private const float RESPONSE_FORWARD_QUADRATIC_STAT_SCALE = 0.2903534174f;
        private const float RESPONSE_FORWARD_SKID_BASE = 0.6150994897f;
        private const float RESPONSE_FORWARD_SKID_STAT_SCALE = 0.9181777835f;
        private const float RESPONSE_FORWARD_SPEED_SCALE = 0.1f;
        private const float RESPONSE_FORWARD_POWDER_DEPTH_BASE = 0.5f;
        private const float RESPONSE_FORWARD_UNCHARGED_DRAG = 0.1057286412f;
        private const float RESPONSE_FORWARD_BOOST_SKID_SCALE = 1.2153687477f;
        private const float RESPONSE_FORWARD_SKID_DRAG = 1.7513076067f;

        // [Trailmap: 330-lateral] Recovered coefficients in the existing metre-based formulation.
        // Speed knots are m/s (about 20 and 50 km/h); slopes multiply m/s to give dimensionless speed gain. Other
        // gains are dimensionless.
        private const float RESPONSE_LATERAL_LOW_SPEED_MPS = 5.555555419922f;
        private const float RESPONSE_LATERAL_MID_SPEED_MPS = 13.888887939453f;
        private const float RESPONSE_LATERAL_LOW_BASE = 0.2010370344f;
        private const float RESPONSE_LATERAL_LOW_SLOPE = 0.0889972609f;
        private const float RESPONSE_LATERAL_MID_BASE = 0.69546628f;
        private const float RESPONSE_LATERAL_MID_SLOPE = 0.0361297949f;
        private const float RESPONSE_LATERAL_HIGH_BASE = 0.9965478778f;
        private const float RESPONSE_LATERAL_HIGH_FALLOFF = 0.01044131714f;
        private const float RESPONSE_LATERAL_RIDER_BASE = 0.0010000000475f;
        private const float RESPONSE_LATERAL_RIDER_STAT_SCALE = 1.1412174702f;
        private const float RESPONSE_LATERAL_BOOST_SCALE = 3.4999945164f;
        private const float RESPONSE_LATERAL_LEAN_SCALE = 1.0001484156f;

        // [Trailmap: 330-yaw] Recovered mode-selected heading curve.
        // Angles are radians; shape and charge scales are dimensionless. Mode numbers are selectors, not verified
        // rider-attribute names.
        private const float RESPONSE_LEAD_MODE2_SHAPE = 0.208338961f;
        private const float RESPONSE_LEAD_MODE0_SHAPE = 0.3001891971f;
        private const float RESPONSE_LEAD_DEFAULT_SHAPE = 0.400000006f;
        private const float RESPONSE_LEAD_MODE2_ANGLE_RAD = 0.2622103095f;
        private const float RESPONSE_LEAD_MODE0_ANGLE_RAD = 0.3491855264f;
        private const float RESPONSE_LEAD_DEFAULT_ANGLE_RAD = 0.5239824057f;
        private const float RESPONSE_LEAD_SHAPE_SCALE = 0.5f;
        private const float RESPONSE_LEAD_CHARGE_SCALE = 0.01f;

        // [Trailmap: 330-yaw / 330-alignment-basis] Recovered heading closure and flat-ground fallback threshold.
        // speedGate multiplies (m/s)^2*seconds; alignSpeedMps is about 20 km/h; capRadPerTick is about 6 degrees
        // per 60 Hz tick, not rad/s. Other values are dimensionless.
        private const float RESPONSE_YAW_SLIP_PROJECTION_LIMIT = 0.99999f;
        private const float RESPONSE_YAW_SPEED_GATE = 0.2002984729f;
        private const float RESPONSE_YAW_ALIGN_SCALE = 40.0f;
        private const float RESPONSE_YAW_ALIGN_SPEED_MPS = 5.555555419922f;
        private const float RESPONSE_YAW_ALIGN_RATIO = 0.5f;
        private const float RESPONSE_YAW_ALIGN_BASE = 0.01004204992f;
        private const float RESPONSE_YAW_CAP_RAD_PER_TICK = 0.104719758f;
        private const float RESPONSE_YAW_FLAT_CROSS_LENGTH_SQ = 1e-08f;

        // [Trailmap: 330-lean / 330-lean-vals] Recovered lean shaping; existing runtime rounding retained.
        // Lean and input are normalized; speed references are m/s; slew rates are lean units/s. Powder keeps the
        // port's 0.5999726 rounding of the spec's 0.599972606.
        private const float RESPONSE_LEAN_SPEED_MODE2_MPS = 11.3827f;
        private const float RESPONSE_LEAN_SPEED_MODE0_MPS = 11.3497f;
        private const float RESPONSE_LEAN_SPEED_DEFAULT_MPS = 11.1901f;
        private const float RESPONSE_LEAN_INPUT_LIMIT = 0.9051856f;
        private const float RESPONSE_LEAN_SLEW_GAIN = 7.017359f;
        private const float RESPONSE_LEAN_SLEW_MIN_PER_SECOND = 0.1f;
        private const float RESPONSE_LEAN_SLEW_MAX_PER_SECOND = 8.018349f;
        private const float RESPONSE_LEAN_POWDER_SLEW_SCALE = 0.5999726f;

        // [Trailmap: 330-bank-force] Recovered banked-contact clamp.
        // Dimensionless multiplier of the surface load acceleration; applied before resolving the banked force.
        private const float RESPONSE_BANK_LOAD_CAP_MULTIPLIER = 2.0f;

        // [Trailmap: 320-spring / 320-spring-accel] Recovered three-zone contact response.
        // aboveLengthCm converts surface A to the above-surface stiffness; deepGain raises the response from A to
        // 3A across the deep zone.
        private const float RESPONSE_CONTACT_ABOVE_LENGTH_CM = 30.0f;
        private const float RESPONSE_CONTACT_DEEP_GAIN = 2.0f;

        // [Trailmap: 320-spring-accel / 330-bank-force] Unit conversion, not ride tuning.
        // Surface A is in centimetres/s^2; divide by centimetresPerMetre to obtain m/s^2.
        private const float RESPONSE_UNITS_CENTIMETRES_PER_METRE = 100.0f;

        // [Trailmap: 330-carve-formula] Project defaults, not recovered retail character statistics.
        // Neutral normalized stats, mode 1, matching edge, unity supplied load ratio and zero skid-control state.
        private const float RESPONSE_DEFAULTS_NORMALIZED_STAT = 0.5f;
        private const int RESPONSE_DEFAULTS_MODE = 1;
        private const int RESPONSE_DEFAULTS_EDGE = 0;
        private const float RESPONSE_DEFAULTS_LOAD_RATIO = 1.0f;
        private const float RESPONSE_DEFAULTS_SKID = 0.0f;

        // [Trailmap: 330-yaw / 330-carve-formula / 320-spring] Project numerical safeguards, not recovered tuning.
        // Separate dimensional floors for yaw direction speed, resistance sink budget, and the slewed contact span
        // (also the Unity bog floor).
        private const float RESPONSE_GUARDS_SPEED_MPS = 1e-06f;
        private const float RESPONSE_GUARDS_BUDGET_METRES = 1e-06f;
        private const float RESPONSE_GUARDS_CONTACT_SPAN_METRES = 0.0001f;

        // [Trailmap: 330-resistance] Project-neutral tuning; not a retail character's statistics.
        [Range(0f, 1f)] public float resistanceLinearStat = RESPONSE_DEFAULTS_NORMALIZED_STAT;
        [Range(0f, 1f)] public float resistanceQuadraticStat = RESPONSE_DEFAULTS_NORMALIZED_STAT;
        [Range(0f, 1f)] public float resistanceSkidStat = RESPONSE_DEFAULTS_NORMALIZED_STAT;
        [Range(0f, 1f)] public float resistanceLateralStat = RESPONSE_DEFAULTS_NORMALIZED_STAT;
        public int resistanceMode = RESPONSE_DEFAULTS_MODE;
        public int resistanceEdge = RESPONSE_DEFAULTS_EDGE;
        public int resistancePreferredEdge = RESPONSE_DEFAULTS_EDGE;
        public float resistanceLoadRatio = RESPONSE_DEFAULTS_LOAD_RATIO;
        public float resistanceSkid = RESPONSE_DEFAULTS_SKID;

        float RideResponseStance()
        {
            if (resistanceEdge == resistancePreferredEdge || resistanceMode == 1) return 1f;
            return resistanceMode == 0 ? RESPONSE_STANCE_MODE0_MISMATCH : RESPONSE_STANCE_OTHER_MISMATCH;
        }

        // [Trailmap: 330-resistance] Velocities, lengths and output acceleration use metres.
        float RideForwardResistance(int row, float u, float error, float budget, float charge, float boost)
        {
            float stance = RideResponseStance();
            float rA = (resistanceMode == 2
                ? RESPONSE_FORWARD_MODE2_LINEAR_BASE - RESPONSE_FORWARD_MODE2_LINEAR_STAT_SCALE * resistanceLinearStat
                : RESPONSE_FORWARD_LINEAR_BASE - RESPONSE_FORWARD_LINEAR_STAT_SCALE * resistanceLinearStat) * stance;
            float rC = (RESPONSE_FORWARD_QUADRATIC_BASE - RESPONSE_FORWARD_QUADRATIC_STAT_SCALE * resistanceQuadraticStat) * stance;
            float rS = (RESPONSE_FORWARD_SKID_BASE + RESPONSE_FORWARD_SKID_STAT_SCALE * resistanceSkidStat) * stance;
            float q = Mathf.Max(1f, resistanceLoadRatio);
            float x = Mathf.Abs(u) * RESPONSE_FORWARD_SPEED_SCALE;
            float depth = row == 3 || row == 4
                ? RESPONSE_FORWARD_POWDER_DEPTH_BASE - error / Mathf.Max(budget, RESPONSE_GUARDS_BUDGET_METRES) : 1f;
            return -u * depth * (q * _rideSurfResistanceA[row] * rA + (1f - charge) * RESPONSE_FORWARD_UNCHARGED_DRAG
                + (1f + boost * RESPONSE_FORWARD_BOOST_SKID_SCALE) * RESPONSE_FORWARD_SKID_DRAG * resistanceSkid * resistanceSkid * rS
                + x * (q * _rideSurfResistanceB[row] + x * q * _rideSurfResistanceC[row] * rC));
        }

        float RideLateralSpeedGain(float u)
        {
            float speed = Mathf.Abs(u);
            if (speed < RESPONSE_LATERAL_LOW_SPEED_MPS)
                return RESPONSE_LATERAL_LOW_BASE + speed * RESPONSE_LATERAL_LOW_SLOPE;
            if (speed < RESPONSE_LATERAL_MID_SPEED_MPS)
                return RESPONSE_LATERAL_MID_BASE + (speed - RESPONSE_LATERAL_LOW_SPEED_MPS) * RESPONSE_LATERAL_MID_SLOPE;
            return RESPONSE_LATERAL_HIGH_BASE - (speed - RESPONSE_LATERAL_MID_SPEED_MPS) * RESPONSE_LATERAL_HIGH_FALLOFF;
        }

        // [Trailmap: 330-lateral] Acceleration; the ground integrator owns the single timestep multiplication.
        float RideLateralResistance(int row, float u, float w, float lean, float boost)
        {
            float rider = (RESPONSE_LATERAL_RIDER_BASE + RESPONSE_LATERAL_RIDER_STAT_SCALE * resistanceLateralStat)
                * RideResponseStance();
            float boostGain = boost > 0f ? 1f / (1f + RESPONSE_LATERAL_BOOST_SCALE * boost) : 1f;
            return -w * _rideSurfDrag[row] * RideLateralSpeedGain(u)
                * Mathf.Max(1f, Mathf.Abs(lean) * RESPONSE_LATERAL_LEAN_SCALE) * rider * boostGain;
        }

        float RideHeadingLead(float lean, float charge)
        {
            float shape = resistanceMode == 2 ? RESPONSE_LEAD_MODE2_SHAPE
                : resistanceMode == 0 ? RESPONSE_LEAD_MODE0_SHAPE : RESPONSE_LEAD_DEFAULT_SHAPE;
            float angleRad = resistanceMode == 2 ? RESPONSE_LEAD_MODE2_ANGLE_RAD
                : resistanceMode == 0 ? RESPONSE_LEAD_MODE0_ANGLE_RAD : RESPONSE_LEAD_DEFAULT_ANGLE_RAD;
            return lean * angleRad * (1f + RESPONSE_LEAD_SHAPE_SCALE * shape * (1f - lean * lean))
                / (1f + charge * RESPONSE_LEAD_CHARGE_SCALE);
        }

        // [Trailmap: 330-yaw] Radians per fixed tick, with full speed and signed contact projections in m/s.
        float RideHeadingYaw(float lean, float lead, float slipProjection, float speed,
            float forwardSpeed, float fallLineSpeed, float dt)
        {
            if (speed < RESPONSE_GUARDS_SPEED_MPS || dt <= 0f) return 0f;
            float candidate = lead - Mathf.Asin(Mathf.Clamp(slipProjection,
                -RESPONSE_YAW_SLIP_PROJECTION_LIMIT, RESPONSE_YAW_SLIP_PROJECTION_LIMIT));
            if (forwardSpeed < 0f) candidate = -candidate;
            float gate = Mathf.Min(1f, speed * speed * RESPONSE_YAW_SPEED_GATE * dt);
            float align = Mathf.Min(1f, Mathf.Max(0f, RESPONSE_YAW_ALIGN_SCALE * Mathf.Min(1f, speed / RESPONSE_YAW_ALIGN_SPEED_MPS)
                * (RESPONSE_YAW_ALIGN_RATIO - Mathf.Abs(fallLineSpeed) / speed)) + RESPONSE_YAW_ALIGN_BASE);
            float gain = Mathf.Max(candidate > 0f ? lean : -lean, align);
            return Mathf.Clamp(candidate * gate * gain, -RESPONSE_YAW_CAP_RAD_PER_TICK, RESPONSE_YAW_CAP_RAD_PER_TICK);
        }

        float RideBankedNormalResponse(float response, float cappedResponse, float theta)
        {
            return response + cappedResponse - cappedResponse / Mathf.Cos(theta);
        }
    }
}
