#!/usr/bin/env python3
"""Generate the three runtime views of the fixed external-sound bank catalog."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys


SLOPESMITH = Path(__file__).resolve().parents[1]
ROOT = SLOPESMITH.parent
SOURCE = ROOT / "Trailmap/specs/data/external-sound-banks-v1.json"
TS_TARGET = SLOPESMITH / "src/core/effects/external-sound-banks.generated.ts"
CS_TARGET = ROOT / "Snowknife/Snowknife/Engine/ExternalSoundCatalog.Generated.cs"
PY_TARGET = ROOT / "Trailmap/tools/autotest/audio_banks_generated.py"


def rows(data: dict) -> list[tuple[int, str]]:
    if data.get("schema") != "external-sound-banks/v1" or data.get("version") != 1:
        raise ValueError("unsupported external-sound bank schema/version")
    if data.get("dynamicSpecialEvents") != [102]:
        raise ValueError("event 102 must remain the sole context-selected special event")
    result = sorted((int(event), bank) for event, bank in data.get("fixedBanks", {}).items())
    if len(result) != 86 or len({event for event, _ in result}) != len(result):
        raise ValueError("fixed bank catalog must contain 86 unique events")
    expected = [*range(79, 97), *range(103, 148), *range(159, 179), *range(183, 186)]
    if [event for event, _ in result] != expected:
        raise ValueError("fixed bank event set is incomplete")
    for event, bank in result:
        if not isinstance(bank, str) or not re.fullmatch(r"[A-Za-z0-9_]{1,32}", bank):
            raise ValueError(f"event {event} is not a short bank/file identifier: {bank!r}")
    return result


def generate_ts(items: list[tuple[int, str]]) -> str:
    lines = [
        "// <auto-generated>",
        "// Generated from Trailmap/specs/data/external-sound-banks-v1.json.",
        "// Short executable/file identifiers only; do not edit this file directly.",
        "// </auto-generated>",
        "",
        "export const FIXED_EXTERNAL_BANKS: Readonly<Record<number, string>> = Object.freeze({",
    ]
    lines.extend(f"  {event}: {json.dumps(bank)}," for event, bank in items)
    lines.extend(["});", ""])
    return "\n".join(lines)


def generate_cs(items: list[tuple[int, str]]) -> str:
    lines = [
        "// <auto-generated>",
        "// Generated from Trailmap/specs/data/external-sound-banks-v1.json.",
        "// Short executable/file identifiers only; do not edit this file directly.",
        "// </auto-generated>",
        "",
        "namespace Snowknife.Engine;",
        "",
        "internal static partial class ExternalSoundCatalog",
        "{",
        "    private static readonly IReadOnlyDictionary<int, string> FixedBanks = new Dictionary<int, string>",
        "    {",
    ]
    lines.extend(f"        {{ {event}, {json.dumps(bank)} }}," for event, bank in items)
    lines.extend(["    };", "}", ""])
    return "\n".join(lines)


def generate_py(items: list[tuple[int, str]]) -> str:
    lines = [
        "# <auto-generated>",
        "# Generated from Trailmap/specs/data/external-sound-banks-v1.json.",
        "# Short executable/file identifiers only; do not edit this file directly.",
        "# </auto-generated>",
        "",
        "SPECIAL_BANKS = {",
    ]
    lines.extend(f"    {event}: {json.dumps(bank)}," for event, bank in items)
    lines.extend(["}", ""])
    return "\n".join(lines)


def emit(path: Path, content: str, check: bool) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return True
    if check:
        print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when a generated view differs")
    parser.add_argument("--catalog", type=Path, default=SOURCE, help="path to the authoritative catalog")
    args = parser.parse_args()
    items = rows(json.loads(args.catalog.read_text(encoding="utf-8")))
    ok = emit(TS_TARGET, generate_ts(items), args.check)
    ok = emit(CS_TARGET, generate_cs(items), args.check) and ok
    ok = emit(PY_TARGET, generate_py(items), args.check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
