#!/usr/bin/env python3
"""Generate runtime views of the shared ride contract.

`Trailmap/specs/data/ride-v1.json` is the single runtime-data source, and the Trailmap
prose specs retain the evidence, uncertainty, and algorithm explanations that should
not be flattened into generated code. The generator lives here, with the consumers,
because the spec is the authority on the game and does not depend on its readers.
Slopesmith is the safe default target; Unity outputs are opt-in so telemetry/spec
iteration cannot trigger a Unity import unexpectedly.

Pass --contract when Trailmap is checked out somewhere other than beside Slopesmith.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


SLOPESMITH = Path(__file__).resolve().parents[1]
ROOT = SLOPESMITH.parent
SOURCE = ROOT / "Trailmap/specs/data/ride-v1.json"
TS_TARGET = SLOPESMITH / "src/app/ride/ride-contract.generated.ts"
UNITY_ROOT = ROOT / "Unity"
UNITY_IMPLEMENTATION = UNITY_ROOT / "Importer/Editor/LevelImporter.cs"
VRC_CS_TARGET = ROOT / "Unity/VRC/Riding/Board/RideableBoard.Contract.Generated.cs"
BASIS_CS_TARGET = ROOT / "Unity/Basis/Riding/BasisBoard.Contract.Generated.cs"
#: The VRC layer's namespace; the generated view is a partial of a type declared inside it.
CS_NAMESPACE = "OpenSlope.VrcPlugin"


# The pointer that travels with the tuning rows wherever they are materialized; the statement itself
# lives once, in each NOTICE's RETAIL-DERIVED FACTS section.
NOTICE = [
    "// Measured retail tuning facts, carried as interoperability data. Authoritative copy:",
    "// Trailmap/specs/data/ride-v1.json; scope: the RETAIL-DERIVED FACTS section of each NOTICE.",
]


def number(value: int | float) -> str:
    if isinstance(value, int):
        return str(value)
    rendered = format(value, ".10g")
    return rendered if "." in rendered or "e" in rendered.lower() else rendered + ".0"


def cs_number(value: int | float) -> str:
    return number(value) + "f"


def constants(data: dict) -> list[tuple[str, int | float | bool]]:
    simulation = data["simulation"]
    gravity = data["gravity"]
    contact = data["contact"]
    speed = data["speed"]
    steering = data["steering"]
    pose = data["pose"]
    return [
        ("SIMULATION_HZ", simulation["hz"]),
        ("MAX_CATCHUP_TICKS", simulation["maxCatchupTicks"]),
        ("AIR_GRAVITY_FALLING", gravity["airFalling"]),
        ("AIR_GRAVITY_RISING", gravity["airRising"]),
        ("GROUND_TANGENTIAL_PULL", gravity["groundTangentialPull"]),
        ("AIR_HORIZONTAL_DRAG", gravity["airHorizontalDrag"]),
        ("GROUND_QUADRATIC_DRAG", gravity["groundQuadraticDrag"]),
        ("CONTACT_REDIRECT", contact["redirect"]),
        ("CONTACT_FIELD_SLEW", contact["surfaceFieldSlew"]),
        ("PUSHOUT_CAP", contact["pushoutCap"]),
        ("CONTACT_SEPARATION_SPEED", contact["separationSpeed"]),
        ("PROBE_ABOVE", contact["probeAbove"]),
        ("PROBE_BELOW", contact["probeBelow"]),
        ("ANALYTIC_NEWTON_ITERATIONS", contact["analyticNewtonIterations"]),
        ("ANALYTIC_RAY_RESIDUAL_MAX", contact["analyticRayResidualMax"]),
        ("TOUCHDOWN_RESPONSE_ERROR", contact["touchdownResponseError"]),
        ("MAX_SPEED", speed["defaultCap"]),
        ("BOOST_MAX_SPEED", speed["boostCap"]),
        ("BOOST_CAP_DECAY", speed["capDecay"]),
        ("RIDER_DRIVE", speed["riderDrive"]),
        ("RIDER_DRIVE_MIN", speed["riderDriveMin"]),
        ("RIDER_DRIVE_SPAN", speed["riderDriveSpan"]),
        ("CRUISE_DEFICIT_MAX", speed["cruiseDeficitMax"]),
        ("BOOST_ACCEL", speed["boostAcceleration"]),
        ("BOOST_LEAN_WINDOW", speed["boostLeanWindow"]),
        ("GROUND_TURN_RATE", steering["groundTurnRateDeg"]),
        ("AIR_TURN_RATE", steering["airTurnRateDeg"]),
        ("STEER_STRENGTH", steering["leadStrength"]),
        ("GRIP_SCALE", steering["gripScale"]),
        ("BANK_MAX", steering["bankMaxDeg"]),
        ("CARVE_SLIDE_SCALE", steering["carveSlideScale"]),
        ("CARVE_SLIDE_SLEW", steering["carveSlideSlew"]),
        ("CARVE_SLIDE_SPEED_GATE", steering["carveSlideSpeedGate"]),
        ("GROUND_ORIENT_GAIN", pose["groundCubicGain"]),
        ("GROUND_ORIENT_RATE_CAP", pose["groundRateCapDeg"]),
        ("AIR_LEVEL_RATE", pose["airLevelRateDeg"]),
        ("ORIENTATION_GRACE", pose["orientationGrace"]),
        ("LAUNCH_WORLD_UP_SPEED", pose["launchWorldUpSpeed"]),
        ("LAUNCH_OUTWARD_SPEED", pose["launchOutwardSpeed"]),
    ]


def generate_ts(data: dict) -> str:
    lines = [
        "// <auto-generated>",
        "// Generated by Slopesmith/tools/generate_ride_contract.py from Trailmap/specs/data/ride-v1.json.",
        "// Do not edit this file directly.",
        "// </auto-generated>",
        "",
        *NOTICE,
        "",
        f"export const RIDE_CONTRACT_SCHEMA = {json.dumps(data['schema'])};",
        f"export const RIDE_CONTRACT_VERSION = {data['version']};",
        f"export const RIDE_CONTRACT_PROFILE = {json.dumps(data['profile'])};",
    ]
    for name, value in constants(data):
        rendered = "true" if value is True else "false" if value is False else number(value)
        lines.append(f"export const RIDE_{name} = {rendered};")
    lines.extend([
        "",
        "export interface RideContractSurfaceRow {",
        "  type: number; name: string; A: number; P: number; bog: number; budget: number; thresh: number;",
        "  lift: number; drag: number; target: number; mult: number; tilt: number;",
        "  resistanceA: number; resistanceB: number; resistanceC: number;",
        "}",
        "",
        "export const RIDE_SURFACE_ROWS: RideContractSurfaceRow[] = [",
    ])
    for row in data["surfaces"]:
        lines.append(
            "  { "
            f"type: {row['type']}, name: {json.dumps(row['name'])}, A: {number(row['A'])}, P: {number(row['P'])}, "
            f"bog: {number(row['bog'])}, budget: {number(row['budget'])}, thresh: {number(row['threshold'])}, "
            f"lift: {number(row['lift'])}, drag: {number(row['drag'])}, target: {number(row['target'])}, "
            f"mult: {number(row['multiplier'])}, tilt: {number(row['tiltDeg'])}, "
            f"resistanceA: {number(row['resistanceA'])}, resistanceB: {number(row['resistanceB'])}, "
            f"resistanceC: {number(row['resistanceC'])} }},"
        )
    lines.extend([
        "];",
        "",
        "export interface RideGoldTakeoff { speed: number; trajectoryPitchDeg: number; boardPitchDeg: number }",
        "export const RIDE_GOLD_SNOWDREAM_TAKEOFFS: RideGoldTakeoff[] = [",
    ])
    for sample in data["gold"]["snowdreamNaturalLips"]:
        lines.append(
            "  { "
            f"speed: {number(sample['speed'])}, trajectoryPitchDeg: {number(sample['trajectoryPitchDeg'])}, "
            f"boardPitchDeg: {number(sample['boardPitchDeg'])} }},"
        )
    lines.extend([
        "];",
        "",
    ])
    return "\n".join(lines)


def cs_array(name: str, rows: list[dict], key: str) -> str:
    values = ", ".join(cs_number(row[key]) for row in rows)
    return f"    private float[] {name} = {{ {values} }};"


def generate_vrc_cs(data: dict) -> str:
    rows = data["surfaces"]
    header = [
        "// <auto-generated>",
        "// Generated by Slopesmith/tools/generate_ride_contract.py from Trailmap/specs/data/ride-v1.json.",
        "// Udon-compatible constants and arrays only. Do not edit this file directly.",
        "// </auto-generated>",
        "",
        *NOTICE,
        "",
    ]
    lines = [
        "public partial class RideableBoard",
        "{",
        f"    private const string RIDE_CONTRACT_SCHEMA = {json.dumps(data['schema'])};",
        f"    private const int RIDE_CONTRACT_VERSION = {data['version']};",
        f"    private const string RIDE_CONTRACT_PROFILE = {json.dumps(data['profile'])};",
    ]
    for name, value in constants(data):
        if isinstance(value, bool):
            lines.append(f"    private const bool RIDE_{name} = {'true' if value else 'false'};")
        elif isinstance(value, int):
            lines.append(f"    private const int RIDE_{name} = {value};")
        else:
            lines.append(f"    private const float RIDE_{name} = {cs_number(value)};")
    lines.extend([
        "",
        cs_array("_rideSurfA", rows, "A"),
        cs_array("_rideSurfP", rows, "P"),
        cs_array("_rideSurfBog", rows, "bog"),
        cs_array("_rideSurfBudget", rows, "budget"),
        cs_array("_rideSurfThresh", rows, "threshold"),
        cs_array("_rideSurfLift", rows, "lift"),
        cs_array("_rideSurfDrag", rows, "drag"),
        cs_array("_rideSurfTarget", rows, "target"),
        cs_array("_rideSurfMult", rows, "multiplier"),
        cs_array("_rideSurfTilt", rows, "tiltDeg"),
        cs_array("_rideSurfResistanceA", rows, "resistanceA"),
        cs_array("_rideSurfResistanceB", rows, "resistanceB"),
        cs_array("_rideSurfResistanceC", rows, "resistanceC"),
        "}",
        "",
        "public partial class TerrainPatches",
        "{",
        f"    private const int RIDE_ANALYTIC_NEWTON_ITERATIONS = {data['contact']['analyticNewtonIterations']};",
        f"    private const float RIDE_ANALYTIC_RAY_RESIDUAL_MAX = {cs_number(data['contact']['analyticRayResidualMax'])};",
        "}",
    ])
    # The Unity layers are namespaced (OpenSlope.Importer/.VRC/.Basis), and the ride contract is a partial
    # of the VRC board, so the generated view has to land in the same namespace or it would be extending a
    # different, empty type. Unity 2022.3 is C# 9, so this is a block namespace and the body is indented.
    body = [f"    {line}" if line else "" for line in lines]
    return "\n".join([*header, f"namespace {CS_NAMESPACE}", "{", *body, "}", ""])


def generate_basis_cs(data: dict) -> str:
    rows = data["surfaces"]
    header = [
        "// <auto-generated>",
        "// Generated by Slopesmith/tools/generate_ride_contract.py from Trailmap/specs/data/ride-v1.json.",
        "// Plain-C# surface data only. Do not edit this file directly.",
        "// </auto-generated>",
        "",
        *NOTICE,
        "",
    ]
    lines = [
        "namespace OpenSlope.BasisPlugin",
        "{",
        "    public partial class BasisBoard",
        "    {",
        f"        private const string RIDE_CONTRACT_SCHEMA = {json.dumps(data['schema'])};",
        f"        private const int RIDE_CONTRACT_VERSION = {data['version']};",
        f"        private const string RIDE_CONTRACT_PROFILE = {json.dumps(data['profile'])};",
        "",
    ]
    lines.extend(f"    {line}" for line in [
        cs_array("_rideSurfA", rows, "A"),
        cs_array("_rideSurfP", rows, "P"),
        cs_array("_rideSurfBog", rows, "bog"),
        cs_array("_rideSurfBudget", rows, "budget"),
        cs_array("_rideSurfThresh", rows, "threshold"),
        cs_array("_rideSurfLift", rows, "lift"),
        cs_array("_rideSurfDrag", rows, "drag"),
        cs_array("_rideSurfTarget", rows, "target"),
        cs_array("_rideSurfMult", rows, "multiplier"),
        cs_array("_rideSurfTilt", rows, "tiltDeg"),
        cs_array("_rideSurfResistanceA", rows, "resistanceA"),
        cs_array("_rideSurfResistanceB", rows, "resistanceB"),
        cs_array("_rideSurfResistanceC", rows, "resistanceC"),
    ])
    lines.extend(["    }", "}", ""])
    return "\n".join([*header, *lines])


def emit(path: Path, content: str, check: bool) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return True
    if check:
        print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files differ")
    parser.add_argument(
        "--contract",
        type=Path,
        default=SOURCE,
        help="path to Trailmap/specs/data/ride-v1.json (default: the sibling checkout)",
    )
    parser.add_argument(
        "--unity",
        action="store_true",
        help="also emit/check the Unity VRC and Basis C# views (opt-in because writing Unity triggers Unity import)",
    )
    args = parser.parse_args()
    data = json.loads(args.contract.read_text(encoding="utf-8"))
    if data.get("schema") != "ride-contract/v1" or data.get("version") != 1:
        raise ValueError("unsupported ride contract schema/version")
    surfaces = data.get("surfaces", [])
    if len(surfaces) != 20 or [row.get("type") for row in surfaces] != list(range(20)):
        raise ValueError("ride contract must contain SurfaceType rows 0..19 in order")
    if data["pose"]["launchOutwardSpeed"] != data["contact"]["separationSpeed"]:
        raise ValueError("pose launchOutwardSpeed must equal contact separationSpeed")
    ok = emit(TS_TARGET, generate_ts(data), args.check)
    if args.unity:
        if not UNITY_IMPLEMENTATION.is_file():
            raise FileNotFoundError(f"required Unity implementation is missing: {UNITY_IMPLEMENTATION}")
        ok = emit(VRC_CS_TARGET, generate_vrc_cs(data), args.check) and ok
        ok = emit(BASIS_CS_TARGET, generate_basis_cs(data), args.check) and ok
        template = Path(__file__).with_name("ride_response.cs.txt").read_text(encoding="utf-8")
        for target, namespace, cls in [
            (VRC_CS_TARGET.with_name("RideableBoard.Response.Generated.cs"), CS_NAMESPACE, "RideableBoard"),
            (BASIS_CS_TARGET.with_name("BasisBoard.Response.Generated.cs"), "OpenSlope.BasisPlugin", "BasisBoard"),
        ]:
            content = template.replace("@NAMESPACE@", namespace).replace("@CLASS@", cls)
            ok = emit(target, content, args.check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
