// <auto-generated>
// Generated by Slopesmith/tools/generate_ride_contract.py from Trailmap/specs/data/ride-v1.json.
// Do not edit this file directly. Recovered values, defaults and guards are labeled separately.
// </auto-generated>

// Measured retail tuning facts, carried as interoperability data. Authoritative copy:
// Trailmap/specs/data/ride-v1.json; scope: the RETAIL-DERIVED FACTS section of each NOTICE.

// [Trailmap: 330-resistance] Recovered coefficients.
// Dimensionless edge-mismatch multipliers; mode 1 or matching edges use unity.
export const STANCE_MODE0_MISMATCH = 0.8499836326;
export const STANCE_OTHER_MISMATCH = 0.699878335;

// [Trailmap: 330-resistance] Recovered coefficients in the existing metre-based formulation.
// Stat and boost scales are dimensionless; speedScale converts m/s to x=abs(u)/10; unchargedDrag and
// skidDrag are in 1/s.
export const FORWARD_MODE2_LINEAR_BASE = 0.707642436;
export const FORWARD_MODE2_LINEAR_STAT_SCALE = 0.3019791245;
export const FORWARD_LINEAR_BASE = 1.0649821758;
export const FORWARD_LINEAR_STAT_SCALE = 0.3084552288;
export const FORWARD_QUADRATIC_BASE = 1.2848105431;
export const FORWARD_QUADRATIC_STAT_SCALE = 0.2903534174;
export const FORWARD_SKID_BASE = 0.6150994897;
export const FORWARD_SKID_STAT_SCALE = 0.9181777835;
export const FORWARD_SPEED_SCALE = 0.1;
export const FORWARD_POWDER_DEPTH_BASE = 0.5;
export const FORWARD_UNCHARGED_DRAG = 0.1057286412;
export const FORWARD_BOOST_SKID_SCALE = 1.2153687477;
export const FORWARD_SKID_DRAG = 1.7513076067;

// [Trailmap: 330-lateral] Recovered coefficients in the existing metre-based formulation.
// Speed knots are m/s (about 20 and 50 km/h); slopes multiply m/s to give dimensionless speed gain. Other
// gains are dimensionless.
export const LATERAL_LOW_SPEED_MPS = 5.555555419922;
export const LATERAL_MID_SPEED_MPS = 13.888887939453;
export const LATERAL_LOW_BASE = 0.2010370344;
export const LATERAL_LOW_SLOPE = 0.0889972609;
export const LATERAL_MID_BASE = 0.69546628;
export const LATERAL_MID_SLOPE = 0.0361297949;
export const LATERAL_HIGH_BASE = 0.9965478778;
export const LATERAL_HIGH_FALLOFF = 0.01044131714;
export const LATERAL_RIDER_BASE = 0.0010000000475;
export const LATERAL_RIDER_STAT_SCALE = 1.1412174702;
export const LATERAL_BOOST_SCALE = 3.4999945164;
export const LATERAL_LEAN_SCALE = 1.0001484156;

// [Trailmap: 330-yaw] Recovered mode-selected heading curve.
// Angles are radians; shape and charge scales are dimensionless. Mode numbers are selectors, not verified
// rider-attribute names.
export const LEAD_MODE2_SHAPE = 0.208338961;
export const LEAD_MODE0_SHAPE = 0.3001891971;
export const LEAD_DEFAULT_SHAPE = 0.400000006;
export const LEAD_MODE2_ANGLE_RAD = 0.2622103095;
export const LEAD_MODE0_ANGLE_RAD = 0.3491855264;
export const LEAD_DEFAULT_ANGLE_RAD = 0.5239824057;
export const LEAD_SHAPE_SCALE = 0.5;
export const LEAD_CHARGE_SCALE = 0.01;

// [Trailmap: 330-yaw / 330-alignment-basis] Recovered heading closure and flat-ground fallback threshold.
// speedGate multiplies (m/s)^2*seconds; alignSpeedMps is about 20 km/h; capRadPerTick is about 6 degrees
// per 60 Hz tick, not rad/s. Other values are dimensionless.
export const YAW_SLIP_PROJECTION_LIMIT = 0.99999;
export const YAW_SPEED_GATE = 0.2002984729;
export const YAW_ALIGN_SCALE = 40.0;
export const YAW_ALIGN_SPEED_MPS = 5.555555419922;
export const YAW_ALIGN_RATIO = 0.5;
export const YAW_ALIGN_BASE = 0.01004204992;
export const YAW_CAP_RAD_PER_TICK = 0.104719758;
export const YAW_FLAT_CROSS_LENGTH_SQ = 1e-08;

// [Trailmap: 330-lean / 330-lean-vals] Recovered lean shaping; existing runtime rounding retained.
// Lean and input are normalized; speed references are m/s; slew rates are lean units/s. Powder keeps the
// port's 0.5999726 rounding of the spec's 0.599972606.
export const LEAN_SPEED_MODE2_MPS = 11.3827;
export const LEAN_SPEED_MODE0_MPS = 11.3497;
export const LEAN_SPEED_DEFAULT_MPS = 11.1901;
export const LEAN_INPUT_LIMIT = 0.9051856;
export const LEAN_SLEW_GAIN = 7.017359;
export const LEAN_SLEW_MIN_PER_SECOND = 0.1;
export const LEAN_SLEW_MAX_PER_SECOND = 8.018349;
export const LEAN_POWDER_SLEW_SCALE = 0.5999726;

// [Trailmap: 330-bank-force] Recovered banked-contact clamp.
// Dimensionless multiplier of the surface load acceleration; applied before resolving the banked force.
export const BANK_LOAD_CAP_MULTIPLIER = 2.0;

// [Trailmap: 320-spring / 320-spring-accel] Recovered three-zone contact response.
// aboveLengthCm converts surface A to the above-surface stiffness; deepGain raises the response from A to
// 3A across the deep zone.
export const CONTACT_ABOVE_LENGTH_CM = 30.0;
export const CONTACT_DEEP_GAIN = 2.0;

// [Trailmap: 320-spring-accel / 330-bank-force] Unit conversion, not ride tuning.
// Surface A is in centimetres/s^2; divide by centimetresPerMetre to obtain m/s^2.
export const UNITS_CENTIMETRES_PER_METRE = 100.0;

// [Trailmap: 330-carve-formula] Project defaults, not recovered retail character statistics.
// Neutral normalized stats, mode 1, matching edge, unity supplied load ratio and zero skid-control state.
export const DEFAULTS_NORMALIZED_STAT = 0.5;
export const DEFAULTS_MODE = 1;
export const DEFAULTS_EDGE = 0;
export const DEFAULTS_LOAD_RATIO = 1.0;
export const DEFAULTS_SKID = 0.0;

// [Trailmap: 330-yaw / 330-carve-formula / 320-spring] Project numerical safeguards, not recovered tuning.
// Separate dimensional floors for yaw direction speed, resistance sink budget, and the slewed contact span
// (also the Unity bog floor).
export const GUARDS_SPEED_MPS = 1e-06;
export const GUARDS_BUDGET_METRES = 1e-06;
export const GUARDS_CONTACT_SPAN_METRES = 0.0001;
